apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-data-to-db
spec:
  podSelector:
    matchLabels:
      app: comment-system
      component: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: comment-system
              component: data
      ports:
        - protocol: TCP
          port: 5432