apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-frontend-to-api
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
      component: api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}
              component: frontend
      ports:
        - protocol: TCP
          port: {{ .Values.service.port | default 8080 }}