apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-frontend
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge