apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: comment-system
    component: data
spec:
  selector:
    app: comment-system
    component: data
  ports:
    - protocol: TCP
      port: {{ .Values.service.data.port | default 8080 }}
      targetPort: {{ .Values.service.data.targetPort | default 8080 }}
  type: {{ .Values.service.data.type | default "ClusterIP" }}