apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-api-to-data
spec:
  podSelector:
    matchLabels:
      app: comment-system
      component: data
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: comment-system
              component: api
      ports:
        - protocol: TCP
          port: {{ .Values.service.data.port | default 8080 }}