apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.size }}
{{- if .Values.postgres.pvc.storageClassName }}
  storageClassName: {{ .Values.postgres.pvc.storageClassName }}
{{- end }}